### ISSUE TITLE
(10월 4주차) 구름 먼데이챌린지☁️

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#101]
[구름 챌린지 링크](https://level.goorm.io/l/challenge)

일시: 10월 17일 오후 9시~11시(2시간)

주말 잘 보내시고 월요일 날 봬용

**Comment by blcklamb** [comment]
<img width="533" alt="스크린샷 2022-10-17 오후 11 08 53" src="https://user-images.githubusercontent.com/92101831/196203216-a587cfbc-5a04-4b10-a342-0ccf30bbca6d.png">

**Comment by ParkJungYoon** [comment]
![image](https://user-images.githubusercontent.com/97580782/196203368-0862cfca-f9c6-45d7-9286-f37290cd3ed6.png)

파뤼 가즈아~

**Comment by Malza0408** [comment]
![제목 없음](https://user-images.githubusercontent.com/82519572/197395898-d805cbe8-b8e8-4d28-9de7-166cdb3b0513.png)

**Comment by s0n9h2** [comment]
![image](https://user-images.githubusercontent.com/50363255/197414567-9c85979c-2afd-4324-b4e6-f675d67e8fb2.png)
