### ISSUE TITLE
(10월 4주차) 복습 주간

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#103]
모임 일시: 10월 21일 10시

이번 시즌 중 스스로 풀지 못한 문제 링크를 댓글로 달아주세요.

모임 때는 해당 문제를 각자 혼자 힘으로 풀어보거나

또는 시간 복잡도를 계산해 본 시도 등을 발표합니다.

**Comment by blcklamb** [comment]
[리모컨](https://www.acmicpc.net/problem/1107)

[파괴되지 않은 건물](https://school.programmers.co.kr/learn/courses/30/lessons/92344)

**Comment by ParkJungYoon** [comment]
[🕹 리모컨](https://www.acmicpc.net/problem/1107)

**Comment by ParkJungYoon** [comment]
puyo puyo 미루고 미루다 드디어 풀었습니다! 야호~ 
그래서 저는 금요일에 추가적으로 다들 풀고 나만 안풀었던 [Z](Z)~ 풀어볼게용

**Comment by blcklamb** [comment]
저는 자바스크립트 코테가 있어서 자바스크립트 기초 문제로 싹 풀어보겠습니다.
[신규 아이디 추천](https://school.programmers.co.kr/learn/courses/30/lessons/72410)
[k번째 수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)

**Comment by Malza0408** [comment]
DFS, BFS 복습할 겸 
[적록색약](https://www.acmicpc.net/problem/10026)
[DFS와 BFS](https://www.acmicpc.net/problem/1260)
문제 풀어볼게요.

**Comment by blcklamb** [comment]
> 저는 자바스크립트 코테가 있어서 자바스크립트 기초 문제로 싹 풀어보겠습니다. [신규 아이디 추천](https://school.programmers.co.kr/learn/courses/30/lessons/72410) [k번째 수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)

<img width="621" alt="image" src="https://user-images.githubusercontent.com/92101831/197100206-42f35f00-bc65-4c34-b69b-008340b05865.png">
1시간 반 걸렸는데 이게 level 1이라니.. 아직 자바스크립트로는 멀었네욥

**Comment by Malza0408** [comment]
![적록색약](https://user-images.githubusercontent.com/82519572/197381355-17818378-d31e-4ed6-ae81-2508fb8c4010.png)
![2](https://user-images.githubusercontent.com/82519572/197381357-295fff20-911f-424a-b207-46b1ed2e1eae.png)

휴!
