### ISSUE TITLE
(10월 5주차) 구름 먼데이챌린지☁️

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#104]
[구름 챌린지 링크](https://level.goorm.io/l/challenge)

일시: 10월 24일 오후 7시~9시(2시간)

참고로 이전 챌린지 코드 풀이를 블로그에 올리고 싶으신 분들께서는 해설강의가 나오고 난 뒤부터 가능하니, 참고바랍니다.

이에 따라 관련 문제 커밋도 한 주 미뤄서 올리는 걸로 해요

(자세한 이야기는 다음 모임 때 하도록 합시다)

시간 잊지말고 월요일에 뵈어요!

**Comment by ParkJungYoon** [comment]
![image](https://user-images.githubusercontent.com/97580782/197521666-78b886a6-1fb6-4a87-85bd-341bb9ff5108.png)

**Comment by blcklamb** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/92101831/197526132-058c40ac-98e1-4574-9d43-35d35c15a3ab.png">

2솔 1 메초
