### ISSUE TITLE
엘리스 모의 코테 3회차

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#11]
늦게 이슈 달아서 죄송합니다🙇‍♀️
모의 코딩테스트에 관련된 질문/의견을 자유롭게 댓글로 남겨주세요.
무사히 풀었다는 캡쳐도 좋습니다👩‍💻

**Comment by blcklamb** [comment]
![image](https://user-images.githubusercontent.com/92101831/173382170-87b0086f-ac5e-4d1a-b7c6-8b84617007bc.png)

까먹고 있다가 늦게 시작하기도 했고, 제출하는 데에 서버 오류가 나서 뒤의 두 문제는 못 풀었습니다

눈물 나네용

**Comment by seogudwns** [comment]
![스크린샷(172)](https://user-images.githubusercontent.com/38065726/173991880-e38e9615-26b8-45f0-a425-9ddde5b972a7.png)
차례대로 100,100,100,30,90 을 받은걸로 기억하는데 점수가 뭔가 좀 이상하네요..?..
