### ISSUE TITLE
2022 SK텔레콤 T-WorX for Developers 챌린지

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#12]
늦게 이슈 올려드려서 죄송합니다🙇‍♀️

짧게나마 후기, 소감만 작성 부탁드려요!

**Comment by blcklamb** [comment]
4문제 중 세 문제는 정말 쉽게 풀 수 있었는데, 마지막 문제가 항상 어려워하던 (예상컨데) DFS, BFS 여서 많이 헤매다가 결국 못 풀었습니다. 

아마도 마지막 문제가 당락을 가를 듯!

특이한 점은 SK텔레콤 맞춤형 문제가 나왔다는 것! 

예를 들면 요금제 관련한 문제가 나와서 이렇게도 문제를 만들 수 있구나라는 생각과 함께 재밌게 풀었던 기억이 납니다!

이런 건 조건문만 잘 만들어서 케이스 분류를 잘 할 수 있다면 무난하지 않았을까하는 생각도 드네용

**Comment by s0n9h2** [comment]
이번에 시험 못봐서 너무 아쉽습니다 ㅠㅠ 다음 기회가 있기를
와 근데 그래도 채정님 4문제 중 3문제 푸셨으면 가능성 있는거 아닌가요?!
두근두근👀

**Comment by seogudwns** [comment]
저도 마찬가지로 마지막 문제만 풀지 않고 종료했습니다! (1시간20분정도 걸림.. 바빠서 고려해야할 사항이 많은 문제를 보니 풀기가 싫어지더군요..ㅋㅋ)
