### ISSUE TITLE
(과제) 프로그래머스 스킬 체크

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#15]
잃어버린 감을 찾기 위해 프로그래머스 문제 세트(입문자용)을 풀어옵니다.

[링크는 여기 있습니다!](https://programmers.co.kr/skill_checks)

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/92101831/177925130-4e956af7-84c1-4e06-908e-2688a2c8597c.png">

문제를 푸셨다면, 소감 및 캡쳐를 코맨트로 달아주세요!

**Comment by Malza0408** [comment]
![스킬 체크 레벨 1](https://user-images.githubusercontent.com/82519572/178149542-9c0686e5-6e4a-4fdf-8a10-2d4f9218f1fd.png)
오랜만이라 그런지 어려웠어요! 다시 익숙해져 나가야겠습니다.

**Comment by ParkJungYoon** [comment]
![image](https://user-images.githubusercontent.com/97580782/178198410-f49f2f96-c083-42e2-a5b2-c652d6adc59a.png)

스킬 체크 완료했습니다!

**Comment by blcklamb** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/92101831/178213548-ffb1f4e3-05bc-4355-8130-a4806b73a38c.png">

두번째 시도로 합격했어요!

첫번째는 초급자치고 엄청 어려웠어서 포기했어요

**Comment by seogudwns** [comment]
![image](https://user-images.githubusercontent.com/38065726/178234103-7a9dd273-2348-4c3d-a6cd-4dfe13a19f7d.png)

예전에 했던거라 인증용으로 올리겠습니다!

**Comment by eikjae** [comment]
![image](https://user-images.githubusercontent.com/77964128/178294186-5fac8a45-6655-46da-90b5-b7a953649796.png)

문제 풀이 인증입니다.

**Comment by s0n9h2** [comment]
![image](https://user-images.githubusercontent.com/50363255/178299175-22c019c2-d996-4470-8ed4-fd8f165264a8.png)
입문자 스킬 체크 완료했습니다!
