### ISSUE TITLE
(프로그래머스) 코딩테스트 실전 대비 모의고사

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#21]
[참고 링크](https://career.programmers.co.kr/competitions/2627)

<img width="590" alt="image" src="https://user-images.githubusercontent.com/92101831/178769733-cbcd0e86-fb30-4ccd-8e90-c669d979e595.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/92101831/178769818-201b1494-53c5-469b-b4e6-0df5ddc8a678.png">

참여 원하시는 분께서는 지원 완료 댓글 남겨주세요!

**Comment by blcklamb** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/92101831/178773282-23768f17-c67d-4877-b435-73e6cb912def.png">

**Comment by Malza0408** [comment]
![제목 없음](https://user-images.githubusercontent.com/82519572/178781000-fb4a3d8d-b174-4d91-aa09-d69846525f1b.png)
지원했습니다 :)

**Comment by seogudwns** [comment]
![image](https://user-images.githubusercontent.com/38065726/178954674-370bc5f3-07da-43da-8d4a-bd6d16b1f38d.png)

**Comment by ParkJungYoon** [comment]
지원했습니다!! 프로그래머스에 모의고사 진행하는 줄 몰랐는데 정보 공유해주셔서 감사해용❤️
![image](https://user-images.githubusercontent.com/97580782/179137856-4bd5e010-2e07-4180-8a63-a28e0c4074d1.png)

**Comment by eikjae** [comment]
![image](https://user-images.githubusercontent.com/77964128/179343366-8b957b41-217d-4fed-8d3c-46224a799a6d.png)

지원 완료했습니다.
