### ISSUE TITLE
(7월 4주차) 자료구조

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#23]
[덱](https://www.acmicpc.net/problem/10866)

[최대 힙](https://www.acmicpc.net/problem/11279)

[에디터](https://www.acmicpc.net/problem/1406)

위 두 문제를 풀고 commit 합니다.

기한은 7월 25일까지!

자유롭게 댓글로 의견을 남겨주세요.

ex. 너무 쉬어요 껌이네~☺️

**Comment by seogudwns** [comment]
덱은 이미 푼거에 쓴거가 그대로 기억에 남아서 약간 더 개선을..!...(시간은 줄지 않고 10kb정도 메모리가 절약되더군요..ㅎㅎ)
최대힙은 이제 easy!
(2문제만 풀면 되긴 하지만..)에디터는 향방향 연결리스트였나? 공부후에 풀고 commit할 예정!

**Comment by blcklamb** [comment]
덱이랑 최대 힙은 어쩌다보니 풀이를 두 개 만들었습니다.

에디터는 다행히 아이디어가 빠르게 생각나서 무사히 풀 수 있었던 것 같아요.

DFS/BFS도 그랬는데 자료구조도 시간 초과가 관건인 것 같습니다.
