### ISSUE TITLE
(7월 4주차) 자료구조_트리

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#27]
[트리 순회](https://www.acmicpc.net/problem/1991)

[이진검색트리](https://www.acmicpc.net/problem/5639)

[외판원 순회](https://www.acmicpc.net/problem/2098)

위 세 문제를 풀고 commit 합니다.

💁‍♀️ 마지막 문제는 챌린지입니다! 선택적으로 푸시면 됩니다.

기한은 7월 28일까지!

자유롭게 댓글로 의견을 남겨주세요.

**Comment by blcklamb** [comment]
이진검색트리 너무 어려워요... 이거 누가 하자 했서....🥲

**Comment by blcklamb** [comment]
[난이도 낮은 외판원 순회 문제](https://www.acmicpc.net/problem/10971)

시간 제한과 메모리 제한, 도시 개수가 낮아진 것말고는 동일한 문제인데 알고리즘 분류가 다른 게 흥미로워서 공유합니다.

물론 풀지는 못했어요!😞

**Comment by seogudwns** [comment]
done.
