### ISSUE TITLE
(7월 5주차) 세그먼트 트리&구현

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#29]
[수열과 쿼리 15](https://www.acmicpc.net/problem/14427)

[연구소](https://www.acmicpc.net/problem/14502)

위 두 문제를 풀고 commit 합니다.

기한은 8월 1일까지!

자유롭게 댓글로 의견을 남겨주세요.

**Comment by seogudwns** [comment]
14427 done.

**Comment by blcklamb** [comment]
이번 문제는 다들 풀기 어려워해서 코드리뷰는 생략하고 마치도록 하겠습니다.
다음에 기회가 되면 세그먼트 트리 다른 문제로 도전해봐요..!
