### ISSUE TITLE
(5주차) 엘리스 그래프 알고리즘 심화

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#3]
5월 24일까지 해당 강의를 수강하고 오시길 바랍니다

강의 수강 후 진도율 캡쳐를 댓글로 남겨주세요.

![image](https://user-images.githubusercontent.com/92101831/169647707-8d875545-00da-4a74-b014-99f29c60e942.png)

**Comment by blcklamb** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/92101831/169800947-489d1b92-d209-4d2b-8e9c-6a80c0c2c13f.png">

수업은 다 들었으나 아직 실습 문제 적용하는 것도 쉽지 않네요🤯

원리는 이해가 되나 이걸 안 보고 로직을 구현할 수 있을지는 아직 모르겠어요 문제에 직접 적용해봐야 감이 확실히 잡힐 것 같습니다!

**Comment by seogudwns** [comment]
![스크린샷(154)](https://user-images.githubusercontent.com/38065726/170029535-f75737bf-f9e4-4d4b-a848-17eb4a133bc3.png)
ㅇㅇ
