### ISSUE TITLE
(기타) 어떤 문제/주제를 풀어야 할까요

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#31]
[기업용 코딩테스트 준비하기 주제](https://velog.io/@cmplxn/%EA%B8%B0%EC%97%85%EC%9A%A9-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%A4%80%EB%B9%84%ED%95%98%EA%B8%B0-%EC%A3%BC%EC%A0%9C)

[코딩테스트 대비를 위한 백준 문제 추천](https://covenant.tistory.com/224)

👆 여기 바로 위 링크에서 알고리즘 태그뿐만 아니라 주제별로 문제를 잘 나눠놓았더라구요

다음 모임 때 혹시 팀원분들께서 원하는 주제가 없다면 여기서 함께 골라도 좋을 것 같아요.

시간되시는 분들께서는 글 한 번 훑어보시고 자유롭게 의견 남겨주시면 정말 좋을 것 같습니다.

**Comment by blcklamb** [comment]
준비 운동 한 문제 + 알고리즘 다지기 기초
ex. [N번째 큰 수](https://www.acmicpc.net/problem/2693) + [감소하는 수](https://www.acmicpc.net/problem/1038)

준비 운동 한 문제 + 최고 빈출 DFS/BFS 또는 DP
ex. [쉽게 푸는 문제](https://www.acmicpc.net/problem/1292) + [퇴사](https://www.acmicpc.net/problem/15486)

이런 식으로 문제 구성하는 것도 좋을 것 같아요

**Comment by Malza0408** [comment]
몸풀기 운동 + 심화문제 방식 좋아요!

**Comment by seogudwns** [comment]
원하는 문제... 음.... 랜덤다이스로 실버 1~3 사이의 몸풀기 1개, 골드 1~3 사이의 메인 1개 하면 어떨까요??! ㅎㅎ
(영어 문제 포함)
