### ISSUE TITLE
(8월 2주차) 기본+DP

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#33]
다음 두 문제를 풀고 8월 8일까지 commit합니다.

지난 두 문제가 난이도가 높은 감이 있어서 이번에는 하향 조정 했습니다.

[연산자 끼워넣기](https://www.acmicpc.net/problem/14888)

[1, 2, 3 더하기 4](https://www.acmicpc.net/problem/15989)

이번에는 다 풀어오시길 바랄게요!

**Comment by seogudwns** [comment]
![image](https://user-images.githubusercontent.com/38065726/182315529-08e66836-e3aa-40ee-ae2f-d46aa0409a80.png)
![image](https://user-images.githubusercontent.com/38065726/182315602-4feb873f-0069-49ac-be72-a61e4c0e3940.png)
ㅇㅅㅇ...
