### ISSUE TITLE
(5주차) 엘리스 모의 코테 2회차

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#4]
모의 코딩테스트에 관련된 질문/의견을 자유롭게 댓글로 남겨주세요.
무사히 풀었다는 캡쳐도 좋습니다👩‍💻

**Comment by seogudwns** [comment]
done. 풀이 자체는 이따가 저녁에 올리겠습닏.

**Comment by s0n9h2** [comment]
![image](https://user-images.githubusercontent.com/50363255/169791758-685240ec-f4c8-4db2-8f28-495b97a60317.png)
꺄 기분좋네요
근데 저번주거 안보고 문제만 봐서 모르겠지만 더 쉬워진 느낌?!

**Comment by blcklamb** [comment]
> ![image](https://user-images.githubusercontent.com/50363255/169791758-685240ec-f4c8-4db2-8f28-495b97a60317.png) 꺄 기분좋네요 근데 저번주거 안보고 문제만 봐서 모르겠지만 더 쉬워진 느낌?!

대봑!!!!! 멋있어요 송희넴!!!!!

**Comment by blcklamb** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/92101831/169847802-add8b1e9-5fe7-43ac-abb6-fd47e6349e4a.png">

재귀는 너무 어렵네요 눈물...
재귀때문에 시간 초과난 것 같아요
너무 아깝다
