### ISSUE TITLE
(8월 3주차) CLASS 3++

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#47]
다음 두 문제를 풀고 8월 22일까지 commit합니다.

CLASS 3++: 

[잃어버린 괄호](https://www.acmicpc.net/problem/1541)

[절댓값 힙](https://www.acmicpc.net/problem/11286)

**Comment by seogudwns** [comment]
![스크린샷(336)](https://user-images.githubusercontent.com/38065726/185285738-91557677-0d0f-445c-a0a4-b8687ae5e4b2.png)
![스크린샷(337)](https://user-images.githubusercontent.com/38065726/185285743-98b4f097-0d28-41e4-ac2a-d3f063c4f94e.png)

**Comment by blcklamb** [comment]
<img width="963" alt="스크린샷 2022-08-21 오전 10 39 46" src="https://user-images.githubusercontent.com/92101831/185832291-fc4f031c-7ffa-4aa7-9c3c-6066f2e48f3e.png">

<img width="789" alt="스크린샷 2022-08-22 오후 12 21 47" src="https://user-images.githubusercontent.com/92101831/185832266-e05563e9-6417-42c9-8403-cab6dda41dca.png">

다 풀었습니다!
