### ISSUE TITLE
(5주차) 랜덤 공통 문제

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#5]
[지름길](https://www.acmicpc.net/problem/1446)

알고리즘 분류
[다이나믹 프로그래밍](https://www.acmicpc.net/problem/tag/25)
[그래프 이론](https://www.acmicpc.net/problem/tag/7)
[다익스트라](https://www.acmicpc.net/problem/tag/22)

해당 문제 푸셨다면 댓글로 남겨주세요!

**Comment by seogudwns** [comment]
done. 까먹고 댓글 안달았네요..ㅎ;
