### ISSUE TITLE
(8월 4주차) CLASS 3++, CLASS 4

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#55]
다음 두 문제를 풀고 8월 25일까지 commit합니다.

CLASS 3++:

[Z](https://www.acmicpc.net/problem/1074)

CLASS 4:

[평범한 배낭](https://www.acmicpc.net/problem/12865)

다 푸시고 댓글로 남겨주세요!

**Comment by s0n9h2** [comment]
두 문제 다 풀었습니당!

![image](https://user-images.githubusercontent.com/50363255/186631958-77e3c1c6-d9c7-4a04-9b0c-a71f4b26b983.png)

![image](https://user-images.githubusercontent.com/50363255/186632133-eef53c32-f843-413e-84fa-2cb06bfaf44f.png)

**Comment by blcklamb** [comment]
<img width="784" alt="스크린샷 2022-08-25 오후 2 32 29" src="https://user-images.githubusercontent.com/92101831/186632464-c60f0363-34d1-4f4d-adaa-ee75d2a2a3fe.png">

<img width="777" alt="스크린샷 2022-08-25 오후 6 43 46" src="https://user-images.githubusercontent.com/92101831/186632443-3a990891-8304-4422-84db-a7da31b7672b.png">

**Comment by seogudwns** [comment]
![1074](https://user-images.githubusercontent.com/38065726/186674229-ae726f4b-cd54-46a5-8006-891fc68ce55e.png)
![image](https://user-images.githubusercontent.com/38065726/186674178-5c66a99b-91cc-48c8-994b-baa058ce5294.png)

bitmasking을 안쓴채로 푼 풀이가 궁금하네요ㅎㅎ 내일 기대해봅니다~~~~
