### ISSUE TITLE
(마무리) 2차 스터디 회고 관련

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#6]
금요일 오전 10시 2차 스터디 마지막 모임이 있습니다.

회고를 먼저 진행한 뒤 공통 문제를 풀어온 사람에 한하여 코드 공유를 진행할 예정입니다.

회고는 KPT 방식으로 진행할 예정이고, 아래 링크를 참고하시면 될 것 같습니다.

[KPT 회고 예시](https://brunch.co.kr/@fromjayden/8)

미리 댓글로 KPT를 작성해주셔도 좋을 것 같아요.

내일 10시에 뵙겠습니다!

**Comment by blcklamb** [comment]
K: 
<개인>
꾸준히 문제를 푸는 습관을 들였다.
solved.ac에서 큰 발전을 이루었다.(골드 입성, 새싹 5단계 달성(32일 연속 풀이))
문제를 보고는 대략적인 알고리즘 파악이 가능하다.(동적계획법, 큐, 그래프 이론)

<팀>
깃허브 레포지토리, 웹후크를 이용해 다른 팀원들의 풀이를 실시간으로 자유롭게 공유했다.
깃허브 레포지토리 운영을 하면서 지난 스터디보다 참여도를 높였다.
코딩테스트, 채용공고 정보를 공유하여 다양한 참여를 했다.
solved.ac 시스템을 잘 활용했다.(라이벌 추월이 큰 동기 부여가 됨)

**Comment by KwanHoo** [comment]
<K>
- 배지 달성하기 같은 목표 설정
    -  강제적으로 하루 한문제씩 풀게됨

**Comment by seogudwns** [comment]
K:
<개인>
- 열심히 문제를 풀었고 지속성이 생기게 되었다.
- 골드 달성!
- 웬만한 알고리즘을 그대로 구현이 가능하게 되었다.(물론 대부분 시간초과이더라..)

<팀>
- 개인이 생각하지 못했던 다양한 풀이를 볼 수 있어서 다들 많은 발전을 했다고 생각된다.

**Comment by eikjae** [comment]
K : 함께 공부하며, 혼자라면 하지 못했을 도전들을 많이 시도할 수 있었다. 풀이 방법을 공유하며 더 좋은 풀이 방법에 대해 고민해 볼 수 있었다.

**Comment by JiwooAn** [comment]
K:
- 혼자일 때보다 꾸준히 문제를 풀 수 있었다.
- 코딩 테스트를 보면서 나의 실력을 알 수 있었다.
- 디스코드에 깃허브 알람이 있어 다른 사람들의 커밋을 보며 동기부여를 받을 수 있었다.

**Comment by s0n9h2** [comment]
<개인>
비록 골드는 달성하지 못했지만 등급이 많이 올랐다.
프로젝트 끝나고 감을 많이 잃은 것 같아 하루 최소 한 문제를 풀었더니 성장이 느껴지는 것 같다.

<팀>
다른 사람들의 풀이를 보며 한 문제를 풀 때 다양한 시각을 기를 수 있었다.
함께 공부하며 동기부여와 자극이 큰 도움이 되었다.
solved.ac 시스템을 이용한 것이 도움이 많이 된 것 같다.

**Comment by blcklamb** [comment]
P:
<개인>
풀기에만 급급하여 기록을 거의 하지 못했다.
엘리스 강의에서 배운 방식(동적계획법 점화식 작성, 그래프 다익스트라, DFS, BFS 기본 코드)만으로는 다양한 문제를 풀 수 없었다.
다양한 알고리즘 이론을 다루지 못했다.
알고리즘 공부 방식으로 30분 이내에 풀지 못하면 답을 보는 방식을 채택했더니 휘발성이 너무 강하다

<팀>
엘리스 일정 자체가 너무 바빠 팀원들이 알고리즘에 집중 못 할 때도 많았다.
공지사항 및 이슈를 잘 작성했다 생각했으나 생각보다 전달이 안되어 빼먹는 경우가 있었다.

**Comment by seogudwns** [comment]
P : 
- 디코에 모각코 음성채널을 초반 이후에 잘 이용하지 않게 되었던 것이 많이 아쉽다.(가끔 들어갔는데 사람이 아무도 없..,,ㅠ)
- 팀 스터디가 협동이 되었기보다 개인 레이스가 되었다는 부분이 좀 아쉽다.

**Comment by KwanHoo** [comment]
Problem :

- 개인 
    - 처음에 목표 설정으로 해둔 이코테를 1회독 못함
        - 주차별로 읽을 페이지를 세분화 해서 목표를 구체화 했으면 좋았을거 같음
    - 풀었던 문제나 학습한 이론을 복습 하는 시간을 가지지 못했음

**Comment by s0n9h2** [comment]
P:불만,문제
문제를 풀고 등급을 올리는 것에 집중하여 개념, 이론 공부를 소홀히 한 것 같다.
(이코테 1회독을 하기로 했는데 필요할 때 대신 엘리스 강의나 구글링을 이용한 것에 아쉬움이 있다)
한 문제를 풀 때 시간을 정하는 편이 좋을 것 같은데 풀 수 있을 것 같은 생각이 들면 계속 붙잡고 있는 것을 고쳐야 할 것 같다.
엘리스 일정이 바빠 프로젝트 기간에는 아예 알고리즘 문제를 풀지 못한 점이 타격이 큰 것 같다.

**Comment by JiwooAn** [comment]
P:
- 프로젝트 기간이 되면서 꾸준히 풀지 못했다.
- 알고리즘을 공부하는 시간이 충분하면서도 짧은 느낌이었다.
- 복습이 없어서 예전에 배웠던 걸 활용하지 못했다.

**Comment by eikjae** [comment]
P : 스터디에 참여하지 못하는 상황이 생기는 것이 아쉬웠으며. 개인적으로 꾸준히 문제를 다루지 못한 점 또한 아쉬웠다.

**Comment by blcklamb** [comment]
T:
<개인>
- 한 알고리즘에 대해 적어도 2주는 잡고 이론과 문제 풀이 시간을 갖으며 기록하는 시간도 갖기
- 실버 02 ~골드 03까지 겁먹지 말고 도전하기
- 다른 답을 참고한 경우 주석을 달 수 있을 정도로 알고리즘 작동 방식을 이해하고 제출하기
- 다른 답을 참고한 경우 2주 내에 복습하기(개인 레포지토리에 이슈로 남겨서 확인)

<팀>
- 디스코드는 공지사항을 확실하게 전달하는 데에 한계가 있으므로 단순히 참고용으로만 남긴다.
- 모임 직후 핵심 과제만을 레이블을 달아 깃허브 이슈에 남겨 놓치지 않도록 한다.
- 문제 푸는 양을 늘리기에 앞서 2주 간격으로 문제 복습 구간을 가진다.

(예시) 
'''
1주차 동적 계획법 + 공통문제 2문제 
2주차 큐/스택 + 공통문제 2문제 
3주차 분할 정복 + 공통문제 1문제 + 동적계획법 공통문제 다시 풀기 및 복습 
4주차 그래프 이론 + 공통문제 1문제 + 큐/스택 공통문제 다시 풀기 및 복습
'''
- 일주일에 적어도 한 문제라도 같이 풀고 커밋하는 것으로 정해 흐름 끊기지 않게 하고 잊어버리지 않게 하기

**Comment by KwanHoo** [comment]
Try:

- 개인
    - solved.ac 시스템 적극 활용해서 문제 재미있게 풀어보기 
        - 클래스, 라이벌, 배지 
- 팀
    -  모각코가 활성
        - 2주에 한번 코딩 테스트 치듯이 주말에 모각코에 모여서 몇문제 시간 정해서 문제 풀어보고 간단하게 공유

**Comment by seogudwns** [comment]
T : 
- 시간이 오래 걸리더라도 정말 난이도 높은 한 문제를 오래 잡아서 공통으로 트라이해보면 좋을 것 같다.(최소 플래1 이상?)
    - 다른 사람이 푼 것을 비교/관찰해보면서 실력을 늘릴 수 있을 방향이라고 생각되기 때문.
- 주기적으로(음.. 2~3일?) 최소 한문제를 풀거나 노력한 것을 commit하는 , 그게 안될 때 벌금걷기도 나쁘지 않은 것 같다.(from 노송희님 다른 스터디) 
    - 참여율을 강제로 높일 수 있는 방법.(첫 번째 제안과 함께 해서 시너지가 생기지 않을까?)

**Comment by JiwooAn** [comment]
T:
- 스터디가 일주일에 두 번일 때, 한 번은 예전에 배웠던 알고리즘 문제를 복습하는 시간을 가진다면 좋을 것 같다.
- 이른 아침에 모각코 타임을 가지면 좋을 것 같다.

**Comment by s0n9h2** [comment]
T:
문제를 풀고 기록하는 것도 중요하다고 생각해서 의무는 아니더라도 해당 문제에 포스팅을 올린 게 있다면 commit할 때나 issue로 같이 공유하는 것도 좋을 것 같다.
개념 공부를 엘리스 강의로 진행했는데 너무 얕게 설명해 준다거나 이해가 되지 않는 부분이 있었어서 차라리 이코테나 다른 유명한 강의로 대체하여 이론을 공부하는 편이 나을 것 같다.
엘리스 교육이 끝나면 시간이 더 많은 만큼 (공통문제 말고) 하루 최소 한 문제, 두 문제 풀이를 목표로 스터디를 진행하면 좋을 것 같다.
다같이 복습하는 시간을 정해두어 이미 푼 공통 문제 중 어려웠던 문제를 (답안 보지 않고) 다시 풀어보는 시간을 가지면 내 실력으로 만드는 데 도움이 될 것 같다.

**Comment by eikjae** [comment]
T : 
개인: 코테 문제를 다루기 위한 시간을 규칙적으로 정해두기 (예: 저녁 7시 ~ 9시는 코테 문제 다루기)
문제를 풀 때, 작은 문제들로 나누어 생각하는 연습 하기 (예: 풀어야 하는 문제 = step1 + step2 + step3)
(잘게 나누면 시간 날 때 마다 틈틈이 시도할 수 있지 않을까 하는 생각에)

팀: 모각코 등 코테를 위해 활용할 수 있는 부분 더 활용하기
