### ISSUE TITLE
(회고) 시즌2를 마치며

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#61]
일시: 8월 31일 17시

시즌2를 해오면서, 그리고 앞으로 해야할 부분에 대해
정리하는 마음가짐으로 회고를 진행합니다.
방식은 KPT를 활용합니다.

[KPT 회고란?](https://brunch.co.kr/@fromjayden/8)

함께 얘기하고 싶은 주제 또는 아이디어가 있다면 자유롭게 댓글로 남겨주세요.

**Comment by blcklamb** [comment]
### 참여율을 높이기 위해 어떻게 해야할까.

그러나 벌금으로 강제성을 두기에는 다소 무리가 있다고 생각.

무단 불참/사유 불참/지각 등의 경우를 나누어 어느 기간동안 가장 벌점이 많이 나온 사람이
- 벌점이 가장 적은 사람의 코드리뷰를 대신해주기
- 알고리즘 이론 한 주제 정리해서 발표하는 시간 갖기
- 등등...

### 목표?
현재 각자 코딩테스트 스터디를 하는 목표가 궁금합니다.

- 기업 코테 통과를 위해
    - 이 경우 현재 출제 경향성을 파악하고 주제를 되짚어보는 시간이 필요할 듯
- 단순히 알고리즘이 재밌어서
    - 이 경우 챌린지 형식으로 AC 레이팅 내기/백준 대회 참여 등의 이벤트도 괜찮을 듯

### 복습
이번에는 난이도가 높은 문제들이 꽤 있었기에
복습 주간이 반드시 필요하다고 판단됩니다.
- 이전 문제들 중 자신의 힘으로 풀지 않은 것들을 모아서 각자 풀어오기
- 새로운 알고리즘 블로그에 기록하기

**Comment by Malza0408** [comment]
K
매주하는 모각코!
상대방의 코드리뷰

**Comment by blcklamb** [comment]
## K
- 일주일에 두 번, 두 문제씩 + 모각코(옵션) 으로 빡센 일정으로 꾸준히 문제를 풀어 감을 잃지 않았습니다.
- 프로그래머스 실전 모의고사 + 모각코 등으로 백준 문제만 다루는 것이 아니라 실전 대비로 한 바 있습니다.
- fork한 뒤 PR하는 방식으로 변경하여 좀 더 오픈소스 프로젝트 형식으로 방식이 전환되었습니다.
    -> 뭔가 있어보이고 개발자에 맞는 스터디 방식인 것 같아요.

**Comment by ParkJungYoon** [comment]
## K
1. 내가 짠 알고리즘을 코드리뷰 하는 것이 좋습니다. 말로 설명하면서 스스로 알고리즘을 복습할 수 있고 더 개선할 부분을 발견할 수 있었습니다. 
2. 다양한 풀이를 볼 수 있어 좋았습니다.

**Comment by seogudwns** [comment]
### K(keep)
- 주기적으로 공통적인 문제를 풀어나간다는 점.(강제성)
- 사람들과 소통하고 있다는 것.
- git을 좀 더 다양하게 이용하게 되었다는 점.

**Comment by s0n9h2** [comment]
## K
- 코드 리뷰 한 명씩 남겨주는 것
- 주간 모임 문제는 백준에서 모각코 문제는 프로그래머스에서 선정하는 것,

**Comment by seogudwns** [comment]
## P(problem)
#### 개인
- 취업에 대한 알고리즘으로써의 지식은 한참 넘게 얻은 것 같은데 오히려 여기에 매몰되었다고 느낌.(혼자 공부한 것 포함, from 면접 피드백)

#### 스터디
- 새로운 알고리즘에 대한 배움(교육)이 없는 상태.

**Comment by s0n9h2** [comment]
## P
- 공통 문제가 난이도가 높은 문제일 때 다들 못 풀어오면 그대로 스터디가 일찍 종료됨
- 풀이법이 비슷할 수밖에 없는 알고리즘은 다른 사람들이 말한 내용을 거의 비슷하게 언급하게 되어 중복되거나 역시 스터디가 일찍 종료됨
- 각자 준비하고 있는 취준 일정이 있기 때문에 참여 인원이 그 때 그 때 달라짐 (어쩔 수 없는 것 같긴 해요)

**Comment by blcklamb** [comment]
## P
- 갑작스러운 불참+스케쥴 조정으로 인한 참여율이 저조했습니다.
    -> 팀장으로서 조금 속상했습니다.
- 일주일에 두 번, 항상 전날에 문제 두 개를 푸는 게 부담스러워서 모임이 잦다고 느껴졌습니다.
- 어려운 문제를 길게 풀 여유가 없어서 항상 모범 코드를 참고하는 것이 부끄럽게 느껴졌습니다.
    -> 어쩔 수 없이 답을 봤다고 했더라고 복습할 시간이 없어서 휘발성이 매우 강했습니다.
- 프로그래머스 실전 모의고사를 풀면서도 실력이 느는 게 느껴지지 않았습니다.
    -> 코딩테스트 스터디에서 얻은 게 무엇인지 고민하게 되었습니다.

**Comment by Malza0408** [comment]
P
개인적인 문제..
종종 나오는 난이도 있는 문제에서 이해를 하지 못하기도 하고, 넘기기도 하는 자신을 발견
다뤘었지만 자꾸 잊는 현상..

**Comment by ParkJungYoon** [comment]
## P
1. 제 실력보다 문제 난이도가 어려운 날에는 시간이 부족해서 답을 보게 되었어요. 저는 조금 더 일반적인 탐색 알고리즘, 구현 (Class3) 난이도를 조금 더 낮춰서 연습하고 싶습니다.
2. 1번에서 마찬가지로 어려워서 급하게 풀고 넘어갔던 문제, 모두가 힘들었던 문제에 대한 복습을 가지는 시간이 없어 비슷한 문제를 만났을 때 해결 능력이 떨어지는 것 같습니다.
3. 모두가 참여할 수 있는 시간대로 스터디 일정 조정이 필요할 것 같습니다.

**Comment by Malza0408** [comment]
T
기간잡고 하나 알고리즘 쭉 부수기
중간 중간 복습기간을 두고 어려웠던 문제 리마인드나 다시풀기
이때 크게 어려운게 없었던 사람은 평소와 같이 다른문제풀이

**Comment by s0n9h2** [comment]
## T
- 모각코 모임날 새로운 문제를 풀기 보다 주간에 푼 4문제 중 가장 어려웠던 혹은 다시 풀어보고 싶은 문제를 선택해 다시 풀어보기로 변경해보는 것
- 코드 리뷰 랜덤 말고 한 명씩 로테이션 방식으로 변경하기 (지금 방식도 상관 없긴 해요)
- 새로 시도하는 알고리즘이나 어려워하는 알고리즘은 미리 개념 설명 동영상이나 블로그로 공부하는 것도 포함시키기, 아니면 아예 초심으로 돌아가서 이코테 책 파트 나눠 정독하고 관련 문제 풀기 (BFS/DFS나 DP 같이 많이 풀어본 알고리즘 외에는 아직도 알고리즘이 익숙하지 않은 것 같아요... 제 기준!)

**Comment by blcklamb** [comment]
## T
1. 난이도의 문제를 해결하기 위해
    - 매 모임마다 랜덤으로 정하기 보다는 사람마다 돌아가면서 미리 문제를 파악해오고, 난이도를 스스로 점검하는 시간을 가진 다음 원하는 난이도 별로 가지고 옵니다. (단, 총 난이도는 실버 4~골드 5로 고정)
    
2. 참여율을 해결하기 위해
    - 주 1회 + 모각코(선택)으로 정하고, 강제성을 부여합니다. (면접, 코테만 허용 가능) 만약 이외 사정으로 불참할 경우 다음 모임 시간에 알고리즘을 하나 정해 발표하는 시간을 갖습니다.(10분 내외) 문제는 두~세 문제!

3. 학습 효율을 높이기 위해+참여율 해결을 위해
    - 2주 간은 공통 문제+모각코 / 3주째는 복습 주간을 가집니다. 복습 주간에는 이전에 답을 참고한 문제에 대해 새로 풀어보거나 복기하는 시간을 가집니다. 모각코 형식으로 진행해서 모여서 각자 공부하는 식으로 강제성 부여 정도로만 모이면 좋을 것 같습니다. 복습이 아니더라도 고급 알고리즘에 대해 공부하는 시간 또는 알고 있는 알고리즘에 대해 문제 푸는 팁을 정리하는 시간을 가지면 좋을 것 같습니다.

**Comment by seogudwns** [comment]
## T(try)
1. 이론에 대해 몇가지를 스터디원당 한가지씩 잡아 일종의 강의 형식으로 모임을 하는 것이 어떨까요? 실력의 부분에서 단순히 문제 하나를 푸는 것 보다는 이게 더 효과적인 선택지 같습니다.
    - 스터디원당 한명씩 강의를 하고 싶은 주제를 선택, 순서를 정해서 모임때 발표 및 질의응답을 하는 식으로..(물론 강의준비가 많을 수록, 그리고 질문을 많이 할수록 효과가 좋습니다. from 교육쪽에서 일해본 경험)
2. (위와 연계해서)못 푼 문제에 대한 복습을 하면 좋을 것 같습니다. 그게 난이도가 어려워서든, 이론이 이해가 안가서든..

#### 추가
- 시즌3은 미참여 예정입니다. 취업하고나서 재미를 위해서라면 몰라도 현재 개인적인 목적과는 맞지 않게 되어서요^^;
- T의 1번에 대해서는 만약 하게 된다면 주제 하나 잡고 강의해드릴 수 있습니다.(세미나 형식, 온라인이든 오프라인이든 어떤 것도 가능하고, 해드리면 좋을 것 같은 주제는 bitmasking이나 segment tree가 있겠네요(둘 다 현재 이 스터디에서 주로 했던 알고리즘이 아니고, 혼자 공부해서 터득한 것이라서요.).)

**Comment by ParkJungYoon** [comment]
## T
1. [문제 유형 제안] 구현, 그리디, DFS/BFS, 이분탐색 등 일반적으로 많이 출제되는 유형을 마스터한 다음 비트마스킹, 백트래킹, 다이나믹 유형을 차근차근 연습하는 방식
2. [스터디 복습 제안] 스터디 중간 중간 복습 주를 포함하여 진행
3. [진행 제안] 어려운 알고리즘이 숙제로 주어진 날에는 다음과 같은 사전 학습도 주어졌으면 좋겠습니다!

`아래: 천준석 님 코딩 테스트 스터디 6팀 README.md`
```
- 숙제 전 사전 학습

구글 "파이썬 딕셔너리 사용" 검색 후 관련 포스팅 보기 실습 무조건 ! => 딕셔너리 접근법 알기 ! 중요중요! key, values, items, dic 만들어보기
구글 "dp(다이나믹 프로그래밍)" 검색 후 관련 포스팅 보기(실습 포함) => 핵심 이해하기(디버깅 중요! 규칙 찾기)
```

이상으로 이렇게 같이 코딩테스트 스터디를 하게 돼서 개인적으로 너무 감사합니다.
깃을 활용해서 이슈 작성해주시고 스터디 이끌어주신 채정님께 정말 감사드립니다.
회고를 통해 더 좋은 방식으로 개선해서 팀원 모두 알고리즘 실력을 향상시키고 앞으로도 같이 스터디 했으면 좋겠습니다.

**Comment by blcklamb** [comment]
## 정리

1️⃣ 개념 공부
기간잡고 하나 알고리즘 쭉 부수기

- 새로 시도하는 알고리즘이나 어려워하는 알고리즘은 미리 개념 설명 동영상이나 블로그로 공부하는 것도 포함시키기, 아니면 아예 초심으로 돌아가서 이코테 책 파트 나눠 정독하고 관련 문제 풀기

- 이론에 대해 몇가지를 스터디원당 한가지씩 잡아 일종의 강의 형식으로 모임을 하는 것이 어떨까요? 실력의 부분에서 단순히 문제 하나를 푸는 것 보다는 이게 더 효과적인 선택지 같습니다.
스터디원당 한명씩 강의를 하고 싶은 주제를 선택, 순서를 정해서 모임때 발표 및 질의응답을 하는 식으로

- [진행 제안] 어려운 알고리즘이 숙제로 주어진 날에는 다음과 같은 사전 학습도 주어졌으면 좋겠습니다! 

2️⃣ 복습 
중간 중간 복습기간을 두고 어려웠던 문제 리마인드나 다시풀기
이때 크게 어려운게 없었던 사람은 평소와 같이 다른문제풀이

- 2주 간은 공통 문제+모각코 / 3주째는 복습 주간을 가집니다. 복습 주간에는 이전에 답을 참고한 문제에 대해 새로 풀어보거나 복기하는 시간을 가집니다. 모각코 형식으로 진행해서 모여서 각자 공부하는 식으로 강제성 부여 정도로만 모이면 좋을 것 같습니다. 복습이 아니더라도 고급 알고리즘에 대해 공부하는 시간 또는 알고 있는 알고리즘에 대해 문제 푸는 팁을 정리하는 시간을 가지면 좋을 것 같습니다.

- 못 푼 문제에 대한 복습을 하면 좋을 것 같습니다. 그게 난이도가 어려워서든, 이론이 이해가 안가서든..

- [스터디 복습 제안] 스터디 중간 중간 복습 주를 포함하여 진행 

3️⃣모각코 
모임날 새로운 문제를 풀기 보다 주간에 푼 4문제 중 가장 어려웠던 혹은 다시 풀어보고 싶은 문제를 선택해 다시 풀어보기로 변경해보는 것

4️⃣코드 리뷰 
랜덤 말고 한 명씩 로테이션 방식으로 변경하기 (지금 방식도 상관 없긴 해요)

5️⃣문제 선정
매 모임마다 랜덤으로 정하기 보다는 사람마다 돌아가면서 미리 문제를 파악해오고, 난이도를 스스로 점검하는 시간을 가진 다음 원하는 난이도 별로 가지고 옵니다.

- [문제 유형 제안] 구현, 그리디, DFS/BFS, 이분탐색 등 일반적으로 많이 출제되는 유형을 마스터한 다음 비트마스킹, 백트래킹, 다이나믹 유형을 차근차근 연습하는 방식

6️⃣일정 변경
주 1회(2~3문제) + 모각코(선택)으로 정하고, 강제성을 부여합니다. (면접, 코테만 허용 가능) 만약 이외 사정으로 불참할 경우 다음 모임 시간에 알고리즘을 하나 정해 발표하는 시간을 갖습니다.(10분 내외)
