### ISSUE TITLE
2023 KAKAO BLIND RECRUITMENT

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#66]
- 접수 일자 : ~ 9월 19일 17시
- 1차 코딩테스트: 9월 24일 (토) 14~19시
- 2차 코딩테스트: 10월 8일 (토) 13~19시
- 1~2차 인터뷰: 10월 말 ~ 11월 초
- 최종 합격 발표: 11월 중
- 입사: 11월 말

[접수 링크](https://career.programmers.co.kr/competitions/2759)

[카카오 코테 연습하러 가기](https://school.programmers.co.kr/learn/challenges)

접수 신청 완료하셨으면 코멘트 부탁드립니다!

**Comment by blcklamb** [comment]
<img width="855" alt="스크린샷 2022-09-10 오후 3 19 31" src="https://user-images.githubusercontent.com/92101831/189471869-a7cfeacc-311b-4bf9-bec1-bc328bae8a4c.png">

**Comment by ParkJungYoon** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/97580782/189471904-9f641edc-502c-47a4-b69d-5635cd81d367.png">

**Comment by Malza0408** [comment]
![카카오 인증](https://user-images.githubusercontent.com/82519572/189473871-9c4e2ccf-3aec-4ffc-a0a5-1fec67d76a72.png)
