### ISSUE TITLE
(9월 2주차) DP + 누적 합

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#71]
모임 일시: 9월 13일 23시

1. DP 문제
    [수익](https://www.acmicpc.net/problem/4097)

2. 누적 합 문제
    [이건 꼭 풀어야 해!](https://www.acmicpc.net/problem/17390)

모두들 추석 잘 보내시고 연휴 끝나고 봐요! 🙋‍♀️

풀었으면 댓글 남겨주세요!

**Comment by Malza0408** [comment]
풀었습니다🙌 연휴에 맞게(?) 많이 어렵진 않은 문제였습니다.

**Comment by blcklamb** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/92101831/189909117-a376837f-c930-4630-801c-dfc67b2ad7dd.png">

🥲

**Comment by ParkJungYoon** [comment]
😱😔
