### ISSUE TITLE
(9월 3주차) 그래프 + DP

### ISSUE THREAD

**Issue by s0n9h2** [elice-02-study-01-algorithm/python#76]
모임 일시: 9월 16일 19시
<br/>

1. 그래프 문제

    [🎨 적록색약](https://www.acmicpc.net/problem/10026)

2. DP

    [🍇 포도주 시식](https://www.acmicpc.net/problem/2156)

<br/>
재밌네요... 제가 고른 문제로 모두가 고통받는다는게...후후 화이팅입니다~!

**Comment by ParkJungYoon** [comment]
재밌네요... dp 고통스러워요 후후

**Comment by blcklamb** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/92101831/190580541-c12e5077-0428-4645-a62f-edaec0bc9abd.png">


<img width="945" alt="image" src="https://user-images.githubusercontent.com/92101831/190580503-501ae7e6-918b-4446-bb09-92792946564a.png">

재밌어요
