### ISSUE TITLE
(9월 4주차) 복습 주간

### ISSUE THREAD

**Issue by blcklamb** [elice-02-study-01-algorithm/python#81]
모임 일시: 9월 19일 18시

지난 시즌 + 이번 시즌 중 스스로 풀지 못한 문제 링크를 댓글로 달아주세요.

모임 때는 해당 문제를 각자 혼자 힘으로 풀어보거나

또는 시간 복잡도를 계산해 본 시도 등을 발표합니다.

복습 주간에 함께 공부할 심화주제는 `비트마스킹`!

**Comment by blcklamb** [comment]
다음 주 카카오 코테인만큼 기출로다가 다시 풀어보겠습니다!

[파괴되지 않은 건물](https://school.programmers.co.kr/learn/courses/30/lessons/92344?language=python3)

[양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)

**Comment by ParkJungYoon** [comment]
떡 먹는 호랑이, 여러분의 다리가 되어 드리겠습니다.
