### ISSUE TITLE
SKTelecom Junior Talent 영입

### ISSUE THREAD

**Issue by s0n9h2** [elice-02-study-01-algorithm/python#88]
## SKTelecom Junior Talent 영입

[채용 공고](http://www.skt-juniortalent.co.kr/) 한 번 읽어보시고 각자 백엔드, 프론트엔드로 지원 완료해주세요😘
코딩테스트는 **10월 9일 오전 11시**이고 그 전인 10월 4일~6일에 **꼭 SKCT를 응시해야 해요**!!!

**Comment by blcklamb** [comment]
SKCT 심층역량 검사: 10월 4일(화) ~ 6일(목) 중 하루
- 지원자마다 응시일자와 시간 상이
- 개별 응시 일시 및 관련 안내 사항은 10월 1일(토) the Careers 마이페이지 ㅌ통해 안내 예정

**Comment by blcklamb** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/92101831/192430201-fc523e56-0b64-4336-8633-dcd97ceef23a.png">

지원할 때 적어야하는 항목 참고하쎄요!
