### ISSUE TITLE
(10월 2주차) 구현 + 정규표현식 

### ISSUE THREAD

**Issue by ParkJungYoon** [elice-02-study-01-algorithm/python#89]
🕢모임 일시: 10월 3일 19시

구현

- [🍗 15686 치킨 배달](https://www.acmicpc.net/problem/15686)

정규표현식

- [🧬 9342 염색체](https://www.acmicpc.net/problem/9342)

---
라인에 문어🐙질 수 없다!!!
화이팅!!! 아자아자
후후후훟후ㅎ후후ㅜ훟 문제 선택하는게 꽤나 재밌네요 훟후ㅜㅎ후ㅜ

**Comment by blcklamb** [comment]
🍗
![image](https://user-images.githubusercontent.com/92101831/193460438-e5787037-2110-4e17-81eb-69d574f45330.png)

🧬
<img width="785" alt="image" src="https://user-images.githubusercontent.com/92101831/193460464-695a0424-1153-4cc6-8fde-d1a28239b754.png">

**Comment by ParkJungYoon** [comment]
문제는 참 좋은데 ㅎ.... 치킨 배달시켜 먹기 참 힘드네여
