### ISSUE TITLE
(10월 2주차) 구현 + 완전탐색

### ISSUE THREAD

**Issue by Malza0408** [elice-02-study-01-algorithm/python#92]
🕢모임 일시: 10월 7일 19시

구현

- [💣 11559 Puyo Puyo](https://www.acmicpc.net/problem/11559)

완전탐색

- [📚 모음사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)

아.. 다음 선택 시에는 실버로 도배하겠습니다.

**Comment by blcklamb** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/92101831/194477366-f09f139a-e70c-4f23-b82b-b0a897e9aaba.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/92101831/194470947-aafd5682-02e1-4d48-b05e-30593a707088.png">

**Comment by Malza0408** [comment]
![1](https://user-images.githubusercontent.com/82519572/194516921-95c7d517-d178-431f-b0c0-3c33b633970a.png)

**Comment by ParkJungYoon** [comment]
┌( ಠ_ಠ)┘
